### PR TITLE
add zstd native build input for NVidia

### LINKED ISSUE #148: failed uncompressing NVIDIA 545.29.06
I get this output:
```
error: builder for '/nix/store/aw669f9bapcvi3pnl494gmbl8gzrln0x-nvidia-x11-545.29.06-nixGL.drv' failed with exit code 2;
       last 10 log lines:
       > Verifying archive integrity... OK
       > Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 545.29.06/nix/store/cjpajrm6h1cqb4kz68x6mq2ilqhr3adn-NVIDIA-Linux-x86_64-545.29.06.run: line 734: /build/makeself.PPNyiBlA/zstd: No such file or directory
       > tail: error writing 'standard output': Broken pipe
       > Extraction failed.
       >
       > Terminated
       > xz: (stdin): File format not recognized
       > tail: error writing 'standard output': Broken pipe
       > tar: This does not look like a tar archive
       > tar: Exiting with failure status due to previous errors
       For full logs, run 'nix log /nix/store/aw669f9bapcvi3pnl494gmbl8gzrln0x-nvidia-x11-545.29.06-nixGL.drv'.
error: 1 dependencies of derivation '/nix/store/a332rx4m3kc2yyns9q3g6n44sx70m0bb-nixGLNvidia-545.29.06.drv' failed to build
```

### PR DESCRIPTION
**Pull request by cmm**
should fix #148

### CODE REVIEW

**Comment by ThomasHauth** [comment]
@cmm Thanks for providing this fix. I ran into the same issue ( #148 ) installing the NVidia driver and this PR fixed it for me.

**Comment by HyperSuperMetaCtrl** [comment]
Ran into the same error. Then tried this patch and it worked

**Comment by liberlanco** [comment]
fixed issue for me  too

**Review by bobvanderlinden — APPROVED** [review]
This worked very nicely for me where-as without this PR nixGL is failing.

```
$ nix run --impure github:nix-community/nixGL -- sweethome3d
...
       > Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 545.29.06/nix/store/cjpajrm6h1cqb4kz68x6mq2ilqhr3adn-NVIDIA-Linux-x86_64-545.29.06.run: line 734: /build/makeself.UcPxplqp/zstd: No such file or directory
       > tail: error writing 'standard output': Broken pipe
       > Extraction failed.
...
```

```
$ nix run --impure github:cmm/nixGL/main -- sweethome3d
... sweethome3d starts
```

**Comment by guibou** [comment]
Thank you.

Blindly merging, I trust you.

**Pull request merged**
